package com.example.nrsimulator

import java.io.BufferedReader
import java.io.InputStreamReader

/**
 * V85 additive NR LDPC base-graph table layer.
 *
 * V82 geometry is preserved. V85 now consumes the complete eight lifting-set
 * shift designs generated by tools/prepare_nr_ldpc_tables.py. The generator
 * uses the MIT-licensed python_5gtoolbox table resources at a pinned commit.
 */
object NrLdpcV85 {
    enum class BaseGraph { BG1, BG2 }

    data class Edge(val row: Int, val column: Int, val shiftsBySet: IntArray) {
        init {
            require(shiftsBySet.size == 8) { "NR LDPC requires eight lifting-set designs" }
            require(row >= 0 && column >= 0)
        }
    }

    data class Table(val rows: Int, val columns: Int, val edges: List<Edge>) {
        fun nonZeroCount(): Int = edges.size
        fun validate(): Boolean {
            if (edges.any { it.row >= rows || it.column >= columns }) return false
            if (edges.map { it.row to it.column }.toSet().size != edges.size) return false
            return edges.all { e -> e.shiftsBySet.all { it >= 0 } }
        }
    }

    fun expectedEdges(bg: BaseGraph): Int = when (bg) {
        BaseGraph.BG1 -> 316
        BaseGraph.BG2 -> 197
    }

    fun expectedGeometry(bg: BaseGraph): Pair<Int, Int> = when (bg) {
        BaseGraph.BG1 -> 46 to 68
        BaseGraph.BG2 -> 42 to 52
    }

    /** Load all eight exact V(i,j) designs from generated resources. */
    fun exactTable(bg: BaseGraph): Table {
        val (rows, columns) = expectedGeometry(bg)
        val matrices = (0..7).map { set -> readMatrix(bg, set, rows, columns) }
        val edges = ArrayList<Edge>(expectedEdges(bg))
        for (r in 0 until rows) {
            for (c in 0 until columns) {
                val shifts = IntArray(8) { set -> matrices[set][r][c] }
                if (shifts[0] >= 0) {
                    require(shifts.all { it >= 0 }) { "Inconsistent V85 edge at ($r,$c)" }
                    edges += Edge(r, c, shifts)
                } else {
                    require(shifts.all { it == -1 }) { "Inconsistent V85 zero entry at ($r,$c)" }
                }
            }
        }
        val table = Table(rows, columns, edges)
        require(validateStandardShape(bg, table)) {
            "Exact V85 table failed ${bg.name} shape/edge validation"
        }
        return table
    }

    fun hasExactTable(bg: BaseGraph): Boolean = runCatching { exactTable(bg); true }.getOrDefault(false)

    /** Gzip+base64 snapshot fallback so a fresh checkout runs without the prep step. */
    private fun embeddedTable(name: String): java.io.ByteArrayInputStream? {
        val packed = NrLdpcV85EmbeddedTables.EMBEDDED[name] ?: return null
        val bytes = java.util.Base64.getDecoder().decode(packed)
        return java.util.zip.GZIPInputStream(bytes.inputStream()).use { gz ->
            java.io.ByteArrayInputStream(gz.readBytes())
        }
    }

    private fun readMatrix(bg: BaseGraph, set: Int, rows: Int, columns: Int): Array<IntArray> {
        val resource = "/nr/ldpc/BG${if (bg == BaseGraph.BG1) 1 else 2}S$set.txt"
        val stream = NrLdpcV85::class.java.getResourceAsStream(resource)
            ?: embeddedTable(resource.removePrefix("/nr/ldpc/").removeSuffix(".txt"))
            ?: error("Missing V85 resource $resource; run tools/prepare_nr_ldpc_tables.py")
        BufferedReader(InputStreamReader(stream, Charsets.UTF_8)).use { reader ->
            val header = reader.readLine() ?: error("Missing V85 header in $resource")
            require(header.startsWith("#")) { "Invalid V85 resource header" }
            val shape = reader.readLine().trim().split(Regex("\\s+"))
            require(shape.size == 2 && shape[0].toInt() == rows && shape[1].toInt() == columns) {
                "Invalid V85 shape in $resource"
            }
            return Array(rows) {
                val values = (reader.readLine() ?: error("Short V85 matrix $resource"))
                    .trim().split(Regex("\\s+")).map(String::toInt)
                require(values.size == columns) { "Invalid V85 row width in $resource" }
                values.toIntArray()
            }
        }
    }

    /** Build the lifted binary parity-check matrix from a validated table. */
    fun lift(table: Table, z: Int, liftingSet: Int): Array<IntArray> {
        require(table.validate()) { "Invalid V85 LDPC table" }
        require(liftingSet in 0..7)
        require(z in NrLdpcV82.allowedLiftingSizes())
        val h = Array(table.rows * z) { IntArray(table.columns * z) }
        for (e in table.edges) {
            val shift = e.shiftsBySet[liftingSet] % z
            for (i in 0 until z) {
                h[e.row * z + i][e.column * z + ((i + shift) % z)] = 1
            }
        }
        return h
    }

    fun validateStandardShape(bg: BaseGraph, table: Table): Boolean {
        val g = expectedGeometry(bg)
        return table.rows == g.first && table.columns == g.second &&
            table.nonZeroCount() == expectedEdges(bg) && table.validate()
    }
}
